### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by pka** [devstructure/blueprint#18] opened 2011-03-24 21:12 UTC
```
$ blueprint create -P test
# [blueprint] searching for Ruby gems
# [blueprint] searching for apt packages
Kein Paket gefunden, das auf ubuntu-desktop passt.
# [blueprint] searching for configuration files
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 53, in <module>
b = blueprint.Blueprint(name=name, create=True)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 67, in __init__
getattr(backend, funcname)(self)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/backend/files.py", line 158, in files
package = _dpkg_query_S(pathname)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/backend/files.py", line 303, in _dpkg_query_S
package, _ = stdout.split(':')
ValueError: too many values to unpack
```

**Comment by rcrowley** [comment] 2011-03-28 23:52
This is a duplicate of #3.

**Closed as completed by rcrowley** 2011-03-28 23:52 UTC
Labels: bug
