### ISSUE TITLE
"ValueError: need more than 1 value to unpack" on Ubuntu Server 10.04

### ISSUE THREAD

**Issue by padenot** [devstructure/blueprint#6] opened 2011-03-22 19:02 UTC
<pre>
└[~]> sudo blueprint create plop -S
# [blueprint] searching for Python packages
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for software built from source
# [blueprint] searching for apt packages
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 53, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 67, in __init__
    getattr(backend, funcname)(self)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/backend/apt.py", line 19, in apt
    s = exclusions()
  File "/usr/local/lib/python2.6/dist-packages/blueprint/backend/apt.py", line 50, in exclusions
    package, property = line.rstrip().split()
ValueError: need more than 1 value to unpack
</pre>

<pre>
└[~]> python --version             
Python 2.6.5
</pre>

**Comment by mrud** [comment] 2011-03-22 22:37
The problem is that you have a package installed without the needed fields. This is probably due to some 3rd party package. 

See issue #8 for a simple fix

**Comment by rcrowley** [comment] 2011-03-22 22:51
Issue #8 includes a fix for this, which I will be verifying and merging as soon as I can.

**Comment by rcrowley** [comment] 2011-03-29 00:55
Simpler protection against missing fields.

Closed by c9a878cc126ad1c63ae052cc2045956ff5176f83.  Closed by c9a878cc126ad1c63ae052cc2045956ff5176f83.

**Closed as completed by rcrowley** 2011-03-29 00:55 UTC
Labels: bug
