### ISSUE TITLE
Shell outputer errors  blueprint show -S <nameofblueprint>

### ISSUE THREAD

**Issue by loque1** [devstructure/blueprint#142] opened 2013-07-11 14:22 UTC
blueprint show -S lo-pc-ihus2
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-show", line 73, in <module>
    filename = getattr(b, options.generate)(options.relaxed).dumpf()
  File "/usr/local/lib/python2.7/dist-packages/blueprint/frontend/sh.py", line 333, in dumpf
    f.write('{0}\n'.format(out))
  File "/usr/lib/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1361: ordinal not in range(128)

**Comment by rcrowley** [comment] 2013-07-11 22:09
Duplicate of #133.

**Closed as completed by rcrowley** 2013-07-11 22:09 UTC
