### ISSUE TITLE
UnicodeDecodeError while creating blueprint


### ISSUE THREAD

**Issue by mback2k** [devstructure/blueprint#80] opened 2011-08-01 19:30 UTC
```
blueprint create test
# [blueprint] using cached blueprintignore rules
# [blueprint] searching for Ruby gems
# [blueprint] searching for APT packages
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for configuration files
# [blueprint] searching for Python packages
# [blueprint] searching for software built from source
# [blueprint] searching for Yum packages
# [blueprint] searching for service dependencies
Traceback (most recent call last):
  File "/usr/bin/blueprint-create", line 61, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/usr/lib/python2.6/dist-packages/blueprint/__init__.py", line 75, in __init__
    services.services(self)
  File "/usr/lib/python2.6/dist-packages/blueprint/services.py", line 80, in services
    b.walk_services(service=service)
  File "/usr/lib/python2.6/dist-packages/blueprint/__init__.py", line 520, in walk_services
    self.walk_services(managername, **kwargs)
  File "/usr/lib/python2.6/dist-packages/blueprint/__init__.py", line 530, in walk_services
    callable(manager, service)
  File "/usr/lib/python2.6/dist-packages/blueprint/services.py", line 78, in service
    b.walk_service_files(manager, service, service_file=service_file)
  File "/usr/lib/python2.6/dist-packages/blueprint/__init__.py", line 549, in walk_service_files
    callable(manager, servicename, pathname)
  File "/usr/lib/python2.6/dist-packages/blueprint/services.py", line 43, in service_file
    if -1 != content.find(dirname):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 560: ordinal not in range(128)
```

**Comment by rcrowley** [comment] 2011-08-02 00:24
Duplicate of #77.

**Closed as completed by rcrowley** 2011-08-02 00:24 UTC
