### ISSUE TITLE
Python Error [IndexError: string index out of range]

### ISSUE THREAD

**Issue by szaydel** [devstructure/blueprint#104] opened 2011-12-06 01:54 UTC
Attempted to create a snapshot as follows on CentOS 6, 64bit, using latest version of blueprint.

[root]⌘ blueprint create --sh --message='Created prior to installation of filebench' bluep-20111205-001
# [blueprint] using cached blueprintignore(5) rules
# [blueprint] searching for npm packages
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for software built from source
# [blueprint] searching for Yum packages
# [blueprint] searching for Ruby gems
# [blueprint] searching for APT packages
# [blueprint] searching for configuration files
# [blueprint] searching for Python packages
# [blueprint] searching for service dependencies

Traceback (most recent call last):
  File "/usr/bin/blueprint-create", line 75, in <module>
    filename = getattr(b, options.generate)(options.relaxed).dumpf()
  File "/usr/lib/python2.6/site-packages/blueprint/**init**.py", line 463, in sh
    return frontend.sh.sh(self, relaxed, server, secret)
  File "/usr/lib/python2.6/site-packages/blueprint/frontend/sh.py", line 186, in sh
    service=service)
  File "/usr/lib/python2.6/site-packages/blueprint/**init**.py", line 493, in walk
    walk.walk(self, *_kwargs)
  File "/usr/lib/python2.6/site-packages/blueprint/walk.py", line 27, in walk
    walk_files(b, *_kwargs)
  File "/usr/lib/python2.6/site-packages/blueprint/walk.py", line 96, in walk_files
    callable(pathname, f)
  File "/usr/lib/python2.6/site-packages/blueprint/frontend/sh.py", line 113, in file
    s.add(_commands, stdin=f['content'], stdout=pathname)
  File "/usr/lib/python2.6/site-packages/blueprint/frontend/sh.py", line 257, in add
    self.out.append(command(_args, **kwargs))
  File "/usr/lib/python2.6/site-packages/blueprint/frontend/sh.py", line 208, in command
    '' if '\n' == stdin[-1] else '\n',
IndexError: string index out of range

**Comment by rcrowley** [comment] 2011-12-07 05:38
I think this is a duplicate of #101, fixed by fb0eb80ec9accac9ee4faf4c35b7c9530f81af39 on master.  The next release will have this fix but we haven't set a date just yet.

**Comment by szaydel** [comment] 2011-12-07 13:47
Sounds good. I must have missed it. Looked over other reports and sure did not see it. Thanks, Sam.

**Closed as completed** 2012-01-26 05:29 UTC
